# Generated by Django 3.2.8 on 2025-04-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('data_acesso', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'access',
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_short_name', models.CharField(max_length=255)),
                ('route_name_start', models.CharField(max_length=255)),
                ('route_name_end', models.CharField(max_length=255)),
                ('route_type', models.IntegerField()),
            ],
            options={
                'db_table': 'bus_routes',
            },
        ),
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('companion', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('slugdiagnostic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cids',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_cidade_origem', models.IntegerField()),
                ('id_cidade_destino', models.IntegerField()),
                ('id_cid', models.IntegerField()),
                ('data_criacao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cidade_origem', models.IntegerField()),
                ('id_cidade_destino', models.IntegerField()),
                ('id_cid', models.IntegerField()),
                ('id_linha', models.CharField(blank=True, max_length=255, null=True)),
                ('sucedida', models.BooleanField()),
                ('data_viagem', models.CharField(max_length=255)),
                ('hora_viagem', models.CharField(max_length=255)),
                ('data_criacao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'searches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
