from core.views.access_view_set import AccessViewSet
from core.views.bus_route_view_set import BusRouteViewSet
from core.views.cid_view_set import CidViewSet
from core.views.city_view_set import CityViewSet
from core.views.group_view_set import GroupViewSet
from core.views.reports_view_set import ReportsViewSet
from core.views.search_view_set import SearchViewSet
from core.views.user_view_set import UserViewSet
from core.views.vehicle_view_set import VehicleViewSet
